### ISSUE TITLE
XATTR testing (Epic)

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#1058]
This is just a tracking ticket for all the tests that need to be implemented for XATTR Sync Gateway testing.

Tickets:
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1045 - Run all tests with XATTRs enabled
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1048 - Test ops present, unprocessed docs 
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1055 - Tests for 'soft' and 'hard' expiry
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1046 - Matrix testing of CRUD ops with SDK
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1054 - Test tombstone handing
- [ ] P2 - https://github.com/couchbaselabs/mobile-testkit/issues/1053 - Processing of external updates with multinode sg clusters
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1051 - High revs XATTRs testing
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1052 - Purge tests with XATTRs
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1025 - Audit Sync Gateway test coverage
- Assigned to Wayne Siu - https://github.com/couchbaselabs/mobile-testkit/issues/1057 - Perf scenario for SDK write -> Sync Gateway _changes
- Assigned to Wayne Siu - https://github.com/couchbaselabs/mobile-testkit/issues/1056 - Test sg performance with XATTRs enabled
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1066 - XATTRs scenario with Sync Gateway and XDCR
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1067 - Autoimport scenarios with SGAccel
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1068 - Matrix testing of CRUD ops with 2 sync gateways
- Descoped https://github.com/couchbaselabs/mobile-testkit/issues/1079 - Sync function scenarios for XATTRs
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1130 - View backfill for deletes
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1174 - Offline external update processing
- [x] https://github.com/couchbaselabs/mobile-testkit/issues/1188 - On demand processing of external updates
