### ISSUE TITLE
[Enhancement] Separate sg_accel and sync_gateway in provisioning conf

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#222]
This will require a fair amount changes in the test scenarios

Instead of 
```
[sync_gateways]
sg1
sg2
sg3

[sync_gateway_index_writers]
sg1
```
Do this
```
[sync_gateways]
sg1
sg2
sg3

[sg_accels]
ac1
ac2
```

### Tasks
- [ ] Separate sync_gateways and sg_accels in provisioning_conf
- [ ] Update generate provisioning script from AWS
- [ ] Refactor out sg_accel provisioning into separate playbooks

**Comment by sethrosetter** [comment]
Fixed via - https://github.com/couchbaselabs/mobile-testkit/pull/410
