### ISSUE TITLE
1.2.1 Android Testing

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#343]
- [x] Run test matrix with Android as SUT using - http://qa.sc.couchbase.com/view/mobile/job/mac-android-node-js-tests-walrus/

- [ ] Review https://github.com/couchbase/couchbase-lite-java-core/issues/976#issuecomment-179706531 - - Stretch goal: Add automated ui test
- [ ] Stretch goal: Add listener test https://github.com/couchbaselabs/sync-gateway-testcluster/issues/325
- [ ] Stretch goal: Add listener test https://github.com/couchbaselabs/sync-gateway-testcluster/issues/326
- [ ] Stretch goal: Add listener test https://github.com/couchbaselabs/sync-gateway-testcluster/issues/327

**Comment by sethrosetter** [comment]
API 23 + SQLite Logs - https://gist.github.com/sethrosetter/0f876f6843ba35b94df1. All failures were reran and they passed except the issues linked above.

**Comment by sethrosetter** [comment]
Concerning issues:
https://github.com/couchbase/couchbase-lite-java-listener/issues/68

**Comment by sethrosetter** [comment]
Using build Android build 1.2.1 + sync_gateway 1.2.0-79

| Storage Type | API 15 | API 19 - armeabi-v7a | API 23 |
|--------|--------|--------|--------|
| SQLite |   |   |   |
| SQCipher |   |   |   |
| ForestDB |  |  |   |
| ForestDB + Encryption |  |  |   |

**Comment by sethrosetter** [comment]
known issues:
cbl-simple-requests.js - couchbase/couchbase-lite-java-core#1110
cbl-document.js -  couchbase/couchbase-lite-android#249

**Comment by sethrosetter** [comment]
Using build Android build 1.2.1 + sync_gateway 1.1.1-10

| Storage Type | API 15 x86 |
|--------|--------|
| SQLite |   | 

Using build Android build 1.2.1 + sync_gateway 1.2.1-4

| Storage Type | API 15 x86 |
|--------|--------|
| SQLite |   |

**Comment by sethrosetter** [comment]
known issues (Failed for all):
cbl-simple-requests.js - couchbase/couchbase-lite-java-core#1110
cbl-document.js - couchbase/couchbase-lite-android#249

**Comment by sethrosetter** [comment]
1** - Reran locally and passed - 
[cbl-large-revisions-compact-revs-limit.txt](https://github.com/couchbaselabs/mobile-testkit/files/198584/cbl-large-revisions-compact-revs-limit.txt)
