### ISSUE TITLE
sync_gateway functional test reorg (stage 1)

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/mobile-testkit#764]
## Stage one (Requirement for 1.4)
- [x] Tag outlier tests
- [x] run all other tests in channel cache / di mode
- [x] base_cc config (1sg_1cbs, first pass channel cache, second pass di)
- [x] base_di config (1sg_1ac_1cbs, first pass channel cache, second pass di)
- [x] reduce code duplication of bootstrapping
- [x] mode flag in runner (could involve tagging parameterization of test)

```
pytest  -s \
        --pdb \
        --mode=cc \
        --server-version=4.5.1-2844 \
        --sync-gateway-version=1.4.0-16 \
        testsuites/syncgateway/functional/
```
